language: ruby
cache: bundler
rvm:
- 2.1.5
before_install: npm install -g grunt-cli
before_script:
- bundle exec rake db:migrate
- npm install
- grunt build
script:
- bundle exec rake spec
- SECRET_KEY_BASE=x DEVISE_SECRET_KEY=x RAILS_ENV=production bundle exec rake assets:precompile
- RAILS_ENV=production bundle exec rake package
notifications:
  email: false
  webhooks: http://n.tkte.ch/h/3277/NNXLHHi3FclU9dLZpLNHByMf
addons:
  code_climate:
    repo_token:
      secure: "n+I0v/sf0MW1GNQ0PIqil/iKg6amBf9/7okjbXgWvK8v7c2XRiQLg+lx53TspuJa6ekmCFMGGfkTStIivDwEoy7r395JmQxnOhToqXQfKWJsDE8WoDSflL3HiJZk8Np09q+KBqkpDFvJAvbmPipmp/cMnERlhkoYjvDAneE2mF8="
