shim: 
  jquery:
    exports: 'jQuery'
  jquery_ujs: ['jquery']
  bootstrap: ['jquery', 'jquery_ujs']
  'twitter/bootstrap/rails/confirm':
    deps: ['bootstrap', 'jquery_ujs']
  'bootstrap/collapse': ['jquery']
  novnc/rfb:
    deps: ["novnc/util","novnc/webutil", "novnc/base64", "novnc/websock", "novnc/des", "novnc/keysymdef", "novnc/keyboard", "novnc/input", "novnc/display", "novnc/jsunzip"]
    exports: 'RFB'
modules:
  - name: 'application'
    include: ['application', 'views/machine/index', 'views/machine/show', 'views/machine/new']
    exclude: []
  - name: 'setup'
    include: ['setup']
preserveLicenseComments: false
generateSourceMaps: true
optimize: uglify2
wrapShim: true